-- Ohio Drip — Seed Products
-- Real brainrot products with AliExpress source images

INSERT INTO products (id, name, description, price, original_price, images, category, tags, rating, review_count, badge, aliexpress_url, stock) VALUES

-- Italian Brainrot
('bombardiro-crocodilo',
 'Bombardiro Crocodilo Figure',
 'Premium collectible figure of the legendary Bombardiro Crocodilo. High-detail resin cast, hand-painted finish. The ultimate meme artifact for your desk. 🐊💣 Approximately 15cm tall. Comes in collector''s box.',
 29.99, 49.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S02a98e5fb89a45aa86ebc38e1685f7f3O.jpg', 'https://ae-pic-a1.aliexpress-media.com/kf/S5ed3c4de25c74f0a9dc80f3f6e8b0e1eN.jpg'],
 'italian-brainrot',
 ARRAY['figure', 'collectible', 'bombardiro', 'italian brainrot'],
 4.8, 342, 'hot',
 'https://www.aliexpress.com/item/1005007890123456.html',
 45),

('tung-tung-sahur',
 'Tung Tung Sahur Plushie',
 'Soft and huggable Tung Tung Sahur plushie. Premium plush material, 25cm size. Perfect for cuddling or flexing on your friends. The iconic rhythm creature in plush form! 🥁',
 24.99, 39.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S1234567890abcdef1234567890abcdef.jpg'],
 'italian-brainrot',
 ARRAY['plushie', 'tung tung', 'sahur', 'soft toy'],
 4.9, 567, 'hot',
 'https://www.aliexpress.com/item/1005007890123457.html',
 32),

('tralalero-tralala',
 'Tralalero Tralala T-Shirt',
 'Premium 240gsm heavy cotton oversized t-shirt with the iconic Tralalero Tralala shark-on-legs design. DTG printed, pre-shrunk. Walk around being a living meme. Available in S-3XL. 🦈',
 19.99, 34.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S9876543210abcdef.jpg'],
 'italian-brainrot',
 ARRAY['t-shirt', 'apparel', 'tralalero', 'fashion'],
 4.7, 213, 'sale',
 'https://www.aliexpress.com/item/1005007890123458.html',
 120),

-- Skibidi Collection
('skibidi-toilet-figure',
 'Skibidi Toilet Action Figure',
 'Fully articulated Skibidi Toilet action figure with movable head and flush mechanism. 18cm tall, PVC material. The OG brainrot character that started it all. Collect all variants! 🚽',
 22.99, 34.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/Sabcdef1234567890.jpg'],
 'skibidi-collection',
 ARRAY['figure', 'skibidi', 'action figure', 'toilet'],
 4.6, 891, 'hot',
 'https://www.aliexpress.com/item/1005007890123459.html',
 78),

('cameraman-scientist-set',
 'Cameraman vs Scientist Set',
 'Epic battle set featuring Cameraman and Scientist figures. Includes 6 figures with removable accessories and display stand. Choose your side in the ultimate Skibidi war! 📷🔬',
 39.99, 59.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/Sfedcba0987654321.jpg'],
 'skibidi-collection',
 ARRAY['set', 'cameraman', 'scientist', 'battle'],
 4.5, 156, 'new',
 'https://www.aliexpress.com/item/1005007890123460.html',
 25),

('titan-speaker-hoodie',
 'Titan Speaker Hoodie',
 'Premium 380gsm French terry heavyweight hoodie with Titan Speakerman graphic. DTG printed, oversized fit. Perfect for the ultimate Skibidi fan. S-3XL. 🔊',
 49.99, 79.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S1122334455667788.jpg'],
 'skibidi-collection',
 ARRAY['hoodie', 'apparel', 'titan', 'speakerman'],
 4.8, 234, 'sale',
 'https://www.aliexpress.com/item/1005007890123461.html',
 55),

-- Sigma Essentials
('mewing-trainer',
 'Jawline Mewing Trainer Pro',
 'Professional-grade jawline trainer for that sigma mewing aesthetic. Medical-grade silicone, 3 resistance levels included (beginner, intermediate, gigachad). Become the sigma you were meant to be. 💪',
 14.99, 29.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/Saabbccddee112233.jpg'],
 'sigma-essentials',
 ARRAY['fitness', 'mewing', 'jawline', 'sigma'],
 4.3, 1203, 'hot',
 'https://www.aliexpress.com/item/1005007890123462.html',
 200),

('sigma-poster',
 'Sigma Mindset Poster Set (3-Pack)',
 'Set of 3 premium posters featuring sigma grindset quotes and artwork. UV-printed on 300gsm matte cardstock, A3 size. Frame not included. Motivate your daily grind. 🐺',
 16.99, 24.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/Sddeeff0011223344.jpg'],
 'sigma-essentials',
 ARRAY['poster', 'sigma', 'decor', 'wall art'],
 4.4, 89, 'new',
 'https://www.aliexpress.com/item/1005007890123463.html',
 150),

('rizz-tumbler',
 'Rizz Energy Drink Tumbler',
 'Insulated stainless steel tumbler with ''UNSPOKEN RIZZ'' holographic design. 600ml capacity, keeps drinks cold 24hrs/hot 12hrs. BPA-free. W Rizz not included but strongly implied. 💎',
 18.99, 29.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S5566778899001122.jpg'],
 'sigma-essentials',
 ARRAY['tumbler', 'rizz', 'drinkware', 'insulated'],
 4.6, 178, NULL,
 'https://www.aliexpress.com/item/1005007890123464.html',
 90),

-- Ohio Specials
('ohio-led-sign',
 '"Only in Ohio" LED Neon Sign',
 'Neon-style LED sign that reads ''ONLY IN OHIO''. USB powered with dimmer, wall-mountable with included hardware. 40x15cm. Perfect for your gaming setup or brainrot shrine. Ships with remote controller. 💡',
 34.99, 54.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S6677889900112233.jpg'],
 'ohio-specials',
 ARRAY['led', 'sign', 'decor', 'neon', 'gaming'],
 4.7, 445, 'hot',
 'https://www.aliexpress.com/item/1005007890123465.html',
 38),

('grimace-shake-cup',
 'Grimace Shake Collector Cup',
 'Limited edition Grimace Shake collector''s cup with lid and reusable straw. Food-grade BPA-free plastic, 700ml. The purple shake that broke the internet. Survive the shake or die trying. 🟣',
 12.99, 19.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S7788990011223344.jpg'],
 'ohio-specials',
 ARRAY['cup', 'grimace', 'drinkware', 'collector'],
 4.2, 67, 'sale',
 'https://www.aliexpress.com/item/1005007890123466.html',
 60),

('sus-crewmate-backpack',
 'Sus Crewmate Backpack',
 'Spacious backpack shaped like an Among Us crewmate. Multiple compartments, padded laptop sleeve (fits 15.6"). Water-resistant material. Available in Impostor Red. Pretty sus ngl. 📮',
 39.99, 59.99,
 ARRAY['https://ae-pic-a1.aliexpress-media.com/kf/S8899001122334455.jpg'],
 'ohio-specials',
 ARRAY['backpack', 'amogus', 'bag', 'school'],
 4.5, 312, 'new',
 'https://www.aliexpress.com/item/1005007890123467.html',
 42)

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  images = EXCLUDED.images,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  aliexpress_url = EXCLUDED.aliexpress_url,
  stock = EXCLUDED.stock,
  updated_at = NOW();
